USE BLOG;

CREATE TABLE BLOG_USER (
	ID_USER INT AUTO_INCREMENT,
    NICKNAME VARCHAR(50) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    CONSTRAINT PK_BLOG_USER PRIMARY KEY (ID_USER),
    CONSTRAINT UQ_BLOG_USER UNIQUE (NICKNAME)
) AUTO_INCREMENT = 100 ENGINE = INNODB DEFAULT CHARACTER SET = utf8mb4;

ALTER TABLE BLOG_USER
MODIFY COLUMN CREATION_DATE TIMESTAMP DEFAULT LOCALTIMESTAMP();

CREATE TABLE POST (
	ID_POST INT AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    POST_NAME VARCHAR(200) NOT NULL,
    POST_BODY TEXT NOT NULL,
    POST_LIKES INT NOT NULL DEFAULT 0,
    POST_DATE TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    CONSTRAINT PK_POST PRIMARY KEY (ID_POST),
    CONSTRAINT UQ_POST UNIQUE (POST_NAME),
    CONSTRAINT CHECK_POST_USER CHECK(EXISTS(SELECT BU.ID_USER FROM BLOG_USER BU WHERE BU.ID_USER = ID_USER)),
    CONSTRAINT FK_POST FOREIGN KEY(ID_USER) REFERENCES BLOG_USER(ID_USER)
) AUTO_INCREMENT = 100 ENGINE = INNODB DEFAULT CHARACTER SET = utf8mb4;

ALTER TABLE POST
ADD CONSTRAINT CHECK_POST_USER CHECK(EXISTS(SELECT BU.ID_USER FROM BLOG_USER BU WHERE BU.ID_USER = ID_USER));

ALTER TABLE POST
CHANGE COLUMN POST_CONTENT POST_BODY TEXT;

ALTER TABLE POST
ADD POST_DATE TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP;

CREATE TABLE POST_COMMENT (
	ID_COMMENT INT AUTO_INCREMENT,
    ID_POST INT NOT NULL,
    ID_USER INT NOT NULL,
    COMMENT_TEXT VARCHAR(300) NOT NULL,
    COMMENT_DATE TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP(),
    CONSTRAINT PK_POST_COMMENT PRIMARY KEY (ID_COMMENT),
    CONSTRAINT FK_POST_COMMENT_POST FOREIGN KEY (ID_POST) REFERENCES POST(ID_POST),
    CONSTRAINT FK_POST_COMMENT_USER FOREIGN KEY (ID_USER) REFERENCES BLOG_USER(ID_USER)
) AUTO_INCREMENT = 100 ENGINE = INNODB DEFAULT CHARACTER SET = utf8mb4;

INSERT INTO BLOG_USER(NICKNAME) 
VALUES 
	('Paulito123');
    
SELECT BU.* FROM BLOG_USER BU;

INSERT INTO POST(ID_USER, POST_NAME, POST_BODY)
VALUES
	(100, );